language: scala

scala:
  - 2.12.3

jdk:
  - oraclejdk8

sudo: true
dist: trusty

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - bin/setupDebian.sh
  - sudo apt-get install -y tree && sudo tree /opt/alterpass